/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BookmarkPage: typeof import('./src/views/BookmarkPage.vue')['default']
    BooksPage: typeof import('./src/views/BooksPage.vue')['default']
    HeaderBar: typeof import('./src/components/HeaderBar.vue')['default']
    HomePage: typeof import('./src/views/HomePage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SetPage: typeof import('./src/views/SetPage.vue')['default']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
  }
}
