/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AlertMeg: typeof import('./src/components/AlertMeg.vue')['default']
    CalendarPage: typeof import('./src/views/CalendarPage.vue')['default']
    CoursePage: typeof import('./src/views/CoursePage.vue')['default']
    HeaderBar: typeof import('./src/components/HeaderBar.vue')['default']
    HomePage: typeof import('./src/views/HomePage.vue')['default']
    ModalDialog: typeof import('./src/components/ModalDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SetPage: typeof import('./src/views/SetPage.vue')['default']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    TaskPage: typeof import('./src/views/TaskPage.vue')['default']
    UserInfo: typeof import('./src/components/UserInfo.vue')['default']
  }
}
